version: '3'
services:

  zookeeper-service:
    container_name: zookeeper
    image: quay.io/debezium/zookeeper:2.3
    ports:
      - ${ZOOKEEPER_PORT}:2181

  kafka-service:
    container_name: kafka
    image: quay.io/debezium/kafka:2.3
    depends_on:
      - zookeeper-service
    ports:
      - ${KAFKA_PORT}:9092
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: LISTENER_INT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INT:PLAINTEXT
      KAFKA_LISTENERS: LISTENER_INT://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INT

  postgres-service:
    container_name: unreal-postgres
    image: quay.io/debezium/postgres:14
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  kafka-connector-service:
    container_name: kafka-connector
    image: quay.io/debezium/connect:2.3
    ports:
      - ${KAFKA_CONNECTOR_PORT}:8083
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
    depends_on:
      - kafka-service
      - postgres-service

  kafdrop-service:
    container_name: kafdrop
    image: obsidiandynamics/kafdrop:latest
    depends_on:
      - kafka-service
    ports:
      - ${KAFDROP_PORT}:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
