version: '3'
services:

  postgres-service:
    container_name: unreal-postgres
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: unreal_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
