spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        default_schema: department
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: ${KAFKA_URL}
